site_name: GraphKB Python
theme:
  name: "material"
  custom_dir: docs/overrides/
repo_url: https://github.com/bcgsc/pori_graphkb_python
repo_name: github
site_dir: build-docs
plugins:
    - redirects:
        redirect_maps:
            # support redirect to the new PORI merged docs site
            usage_examples/tutorial.md: https://bcgsc.github.io/pori/graphkb/scripting/intro_tutorial/
            usage_examples/intro_tutorial.md: https://bcgsc.github.io/pori/graphkb/scripting/intro_tutorial/
            matching/index.md: https://bcgsc.github.io/pori/graphkb/matching/
            matching/: https://bcgsc.github.io/pori/graphkb/matching/
            matching/gene.md: https://bcgsc.github.io/pori/graphkb/matching/gene/
            usage_examples/snpsift/: https://bcgsc.github.io/pori/graphkb/scripting/snpsift/
            usage_examples/variant_strings/: https://bcgsc.github.io/pori/graphkb/scripting/variant_strings/
nav:
  - index.md
